### ISSUE TITLE
Cannot access offset of type string on string

### ISSUE THREAD

**Issue by Miro-Collas** [zteeed/dokuwiki-discord-notifier#26]
See https://prnt.sc/0dV0wG5s4fHC 

I get this on a single page of our wiki (which is quite large) so that suggests something on the page is causing the problem. However, a search turned up this:
https://laracasts.com/discuss/channels/general-discussion/error-after-update-php-73-to-81-cannot-access-offset-of-type-string-on-string

We do in fact use PHP8. So possibly something on the specific page is triggering the behavior described above.

```
2023-08-13 02:38:59TypeError: Cannot access offset of type string on string /home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(113)
    #0 /home/fswiki/public_html/lib/plugins/discordnotifier/action.php(37): helper_plugin_discordnotifier->set_payload_text(Object(dokuwiki\Extension\Event))
    #1 /home/fswiki/public_html/inc/Extension/EventHandler.php(81): action_plugin_discordnotifier->_handle(Object(dokuwiki\Extension\Event), NULL)
    #2 /home/fswiki/public_html/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER')
    #3 /home/fswiki/public_html/inc/File/PageFile.php(194): dokuwiki\Extension\Event->advise_after()
    #4 /home/fswiki/public_html/inc/common.php(1269): dokuwiki\File\PageFile->saveWikiText('{{tag>downloads...', 'created', false)
    #5 /home/fswiki/public_html/inc/Action/Save.php(55): saveWikiText('fs_older_downlo...', '{{tag>downloads...', 'created', false)
    #6 /home/fswiki/public_html/inc/ActionRouter.php(83): dokuwiki\Action\Save->preProcess()
    #7 /home/fswiki/public_html/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction('save')
    #8 /home/fswiki/public_html/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct()
    #9 /home/fswiki/public_html/inc/actions.php(16): dokuwiki\ActionRouter::getInstance(true)
    #10 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #11 {main} 
```

**Comment by yaynstuff** [comment]
Chiming in here (projects sysadmin)

Despite dokuwiki saying we had the most current version of this plugin, it seems that helper.php in our case did not have this fix applied to it:

https://github.com/zteeed/dokuwiki-discord-notifier/commit/d01536c9ae7661e1fff2168dc51984fdff844cf4

I have manually applied this change however it does not resolve the problem, the error remains exactly the same.

**Comment by Miro-Collas** [comment]
This has since happened on a few other pages (we have a many page updates ongoing)

**Comment by Miro-Collas** [comment]
OK, very simple repro: create a new page, type "test" into the contents, save, and you get the error reported above.
If you hit Back on your web browser, you can save. However, the page has actually been created, as you can see if you instead just load visit the page.

**Comment by Miro-Collas** [comment]
warning remain - apparently I didn't fix them all:

```
2023-09-01 21:51:11E_WARNING: Trying to access array offset on value of type null/home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(37)
    #0 /home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(37): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/home/fswiki/pu...', 37)
    #1 /home/fswiki/public_html/lib/plugins/discordnotifier/action.php(31): helper_plugin_discordnotifier->valid_namespace()
    #2 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_discordnotifier->_handle(Object(dokuwiki\Extension\Event), NULL)
    #3 /home/fswiki/public_html/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER')
    #4 /home/fswiki/public_html/inc/File/PageFile.php(194): dokuwiki\Extension\Event->advise_after()
    #5 /home/fswiki/public_html/inc/common.php(1289): dokuwiki\File\PageFile->saveWikiText('test 2', '\xE2\x86\xB7 Page name c...', false)
    #6 /home/fswiki/public_html/lib/plugins/move/helper/op.php(200): saveWikiText('support:test', 'test 2', '\xE2\x86\xB7 Page name c...')
    #7 /home/fswiki/public_html/lib/plugins/move/action/rename.php(117): helper_plugin_move_op->movePage('support:test1', 'support:test')
    #8 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_move_rename->handle_ajax(Object(dokuwiki\Extension\Event), NULL)
    #9 /home/fswiki/public_html/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
    #10 /home/fswiki/public_html/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
    #11 /home/fswiki/public_html/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct('plugin_move_ren...')
    #12 {main}
2023-09-01 21:51:11E_WARNING: Trying to access array offset on value of type null/home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(102)
    #0 /home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(102): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/home/fswiki/pu...', 102)
    #1 /home/fswiki/public_html/lib/plugins/discordnotifier/action.php(37): helper_plugin_discordnotifier->set_payload_text(Object(dokuwiki\Extension\Event))
    #2 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_discordnotifier->_handle(Object(dokuwiki\Extension\Event), NULL)
    #3 /home/fswiki/public_html/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER')
    #4 /home/fswiki/public_html/inc/File/PageFile.php(194): dokuwiki\Extension\Event->advise_after()
    #5 /home/fswiki/public_html/inc/common.php(1289): dokuwiki\File\PageFile->saveWikiText('test 2', '\xE2\x86\xB7 Page name c...', false)
    #6 /home/fswiki/public_html/lib/plugins/move/helper/op.php(200): saveWikiText('support:test', 'test 2', '\xE2\x86\xB7 Page name c...')
    #7 /home/fswiki/public_html/lib/plugins/move/action/rename.php(117): helper_plugin_move_op->movePage('support:test1', 'support:test')
    #8 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_move_rename->handle_ajax(Object(dokuwiki\Extension\Event), NULL)
    #9 /home/fswiki/public_html/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
    #10 /home/fswiki/public_html/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
    #11 /home/fswiki/public_html/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct('plugin_move_ren...')
    #12 {main}
2023-09-01 21:51:11E_WARNING: Trying to access array offset on value of type null/home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(102)
    #0 /home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(102): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/home/fswiki/pu...', 102)
    #1 /home/fswiki/public_html/lib/plugins/discordnotifier/action.php(37): helper_plugin_discordnotifier->set_payload_text(Object(dokuwiki\Extension\Event))
    #2 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_discordnotifier->_handle(Object(dokuwiki\Extension\Event), NULL)
    #3 /home/fswiki/public_html/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER')
    #4 /home/fswiki/public_html/inc/File/PageFile.php(194): dokuwiki\Extension\Event->advise_after()
    #5 /home/fswiki/public_html/inc/common.php(1289): dokuwiki\File\PageFile->saveWikiText('test 2', '\xE2\x86\xB7 Page name c...', false)
    #6 /home/fswiki/public_html/lib/plugins/move/helper/op.php(200): saveWikiText('support:test', 'test 2', '\xE2\x86\xB7 Page name c...')
    #7 /home/fswiki/public_html/lib/plugins/move/action/rename.php(117): helper_plugin_move_op->movePage('support:test1', 'support:test')
    #8 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_move_rename->handle_ajax(Object(dokuwiki\Extension\Event), NULL)
    #9 /home/fswiki/public_html/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
    #10 /home/fswiki/public_html/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
    #11 /home/fswiki/public_html/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct('plugin_move_ren...')
    #12 {main}
2023-09-01 21:51:11E_WARNING: Trying to access array offset on value of type null/home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(113)
    #0 /home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(113): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/home/fswiki/pu...', 113)
    #1 /home/fswiki/public_html/lib/plugins/discordnotifier/action.php(37): helper_plugin_discordnotifier->set_payload_text(Object(dokuwiki\Extension\Event))
    #2 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_discordnotifier->_handle(Object(dokuwiki\Extension\Event), NULL)
    #3 /home/fswiki/public_html/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER')
    #4 /home/fswiki/public_html/inc/File/PageFile.php(194): dokuwiki\Extension\Event->advise_after()
    #5 /home/fswiki/public_html/inc/common.php(1289): dokuwiki\File\PageFile->saveWikiText('test 2', '\xE2\x86\xB7 Page name c...', false)
    #6 /home/fswiki/public_html/lib/plugins/move/helper/op.php(200): saveWikiText('support:test', 'test 2', '\xE2\x86\xB7 Page name c...')
    #7 /home/fswiki/public_html/lib/plugins/move/action/rename.php(117): helper_plugin_move_op->movePage('support:test1', 'support:test')
    #8 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_move_rename->handle_ajax(Object(dokuwiki\Extension\Event), NULL)
    #9 /home/fswiki/public_html/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
    #10 /home/fswiki/public_html/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
    #11 /home/fswiki/public_html/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct('plugin_move_ren...')
    #12 {main}
2023-09-01 21:51:11E_WARNING: Trying to access array offset on value of type null/home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(37)
    #0 /home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(37): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/home/fswiki/pu...', 37)
    #1 /home/fswiki/public_html/lib/plugins/discordnotifier/action.php(31): helper_plugin_discordnotifier->valid_namespace()
    #2 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_discordnotifier->_handle(Object(dokuwiki\Extension\Event), NULL)
    #3 /home/fswiki/public_html/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER')
    #4 /home/fswiki/public_html/inc/File/PageFile.php(194): dokuwiki\Extension\Event->advise_after()
    #5 /home/fswiki/public_html/inc/common.php(1289): dokuwiki\File\PageFile->saveWikiText('', '\xE2\x86\xB7 Page name c...', false)
    #6 /home/fswiki/public_html/lib/plugins/move/helper/op.php(204): saveWikiText('support:test1', '', '\xE2\x86\xB7 Page name c...')
    #7 /home/fswiki/public_html/lib/plugins/move/action/rename.php(117): helper_plugin_move_op->movePage('support:test1', 'support:test')
    #8 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_move_rename->handle_ajax(Object(dokuwiki\Extension\Event), NULL)
    #9 /home/fswiki/public_html/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
    #10 /home/fswiki/public_html/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
    #11 /home/fswiki/public_html/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct('plugin_move_ren...')
    #12 {main}
2023-09-01 21:51:11E_WARNING: Trying to access array offset on value of type null/home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(102)
    #0 /home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(102): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/home/fswiki/pu...', 102)
    #1 /home/fswiki/public_html/lib/plugins/discordnotifier/action.php(37): helper_plugin_discordnotifier->set_payload_text(Object(dokuwiki\Extension\Event))
    #2 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_discordnotifier->_handle(Object(dokuwiki\Extension\Event), NULL)
    #3 /home/fswiki/public_html/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER')
    #4 /home/fswiki/public_html/inc/File/PageFile.php(194): dokuwiki\Extension\Event->advise_after()
    #5 /home/fswiki/public_html/inc/common.php(1289): dokuwiki\File\PageFile->saveWikiText('', '\xE2\x86\xB7 Page name c...', false)
    #6 /home/fswiki/public_html/lib/plugins/move/helper/op.php(204): saveWikiText('support:test1', '', '\xE2\x86\xB7 Page name c...')
    #7 /home/fswiki/public_html/lib/plugins/move/action/rename.php(117): helper_plugin_move_op->movePage('support:test1', 'support:test')
    #8 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_move_rename->handle_ajax(Object(dokuwiki\Extension\Event), NULL)
    #9 /home/fswiki/public_html/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
    #10 /home/fswiki/public_html/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
    #11 /home/fswiki/public_html/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct('plugin_move_ren...')
    #12 {main}
2023-09-01 21:51:11E_WARNING: Trying to access array offset on value of type null/home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(102)
    #0 /home/fswiki/public_html/lib/plugins/discordnotifier/helper.php(102): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/home/fswiki/pu...', 102)
    #1 /home/fswiki/public_html/lib/plugins/discordnotifier/action.php(37): helper_plugin_discordnotifier->set_payload_text(Object(dokuwiki\Extension\Event))
    #2 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_discordnotifier->_handle(Object(dokuwiki\Extension\Event), NULL)
    #3 /home/fswiki/public_html/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER')
    #4 /home/fswiki/public_html/inc/File/PageFile.php(194): dokuwiki\Extension\Event->advise_after()
    #5 /home/fswiki/public_html/inc/common.php(1289): dokuwiki\File\PageFile->saveWikiText('', '\xE2\x86\xB7 Page name c...', false)
    #6 /home/fswiki/public_html/lib/plugins/move/helper/op.php(204): saveWikiText('support:test1', '', '\xE2\x86\xB7 Page name c...')
    #7 /home/fswiki/public_html/lib/plugins/move/action/rename.php(117): helper_plugin_move_op->movePage('support:test1', 'support:test')
    #8 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_move_rename->handle_ajax(Object(dokuwiki\Extension\Event), NULL)
    #9 /home/fswiki/public_html/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
    #10 /home/fswiki/public_html/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
    #11 /home/fswiki/public_html/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct('plugin_move_ren...')
    #12 {main}
```
